sentry:
  dsn: "{SENTRY_DSN}"
  release:
    name: "{SENTRY_RELEASE_NAME}"
# This one is optional ... only if you want to use ai-story command
openAi:
  token: process.env.OPEN
amqp:
  url: process.env.AMQP
discord:
  token: process.env.TOKEN
deploy:
  port: 3000
mongo:
  uri: process.env.MONGO
wombo-dream:
  api:
    url: "https://paint.api.wombo.ai/api"
  googleAuthUrl: "https://www.googleapis.com/identitytoolkit/v3/relyingparty/signupNewUser?key=AIzaSyDCvp5MTJLUdtBYEKYWXJrlLzu1zuKM6Xw"
